# Create a WordPress site out of thin air
#
# TODO: This uses jahia2wp and we don't want to do things this way anymore.

- include_vars: jahia2wp-vars.yml
- include_vars: wp-destructive.yml

- name: Create directories for wordpress instances
  connection: local
  shell: |
    set -e -x
    docker exec "{{nas_name}}" /bin/bash -c 'mkdir -p /"{{nfs_path}}"/wp/"{{name}}" ; chown -R "{{web_uid}}"."{{web_gid}}" /"{{nfs_path}}"/wp'
  when: is_minishift_instance

- name: Create databases for wordpress instances
  connection: local
  shell: |
    set -e -x
    docker exec "{{ msql_name }}" /bin/bash -c 'mysql -u root --password=root! -h {{ db_ip }} -e "CREATE DATABASE IF NOT EXISTS {{ name }}"' 
   
  when: is_minishift_instance

- meta: end_play

- assert:
    that:
      - (wp_can.wipe) or (not _wp_config_php_stat.stat.exists)

- name: Create auxiliary YAML file for "jahia2wp.py generate"
  when: wp_restore_from == 'generate' and not is_minishift_instance
  copy:
    content: |
      langs: en,fr
      unit_name: {{wp_unit_name}}
      unit_id: {{wp_unit_id}}
    dest: "{{ ansible_remote_tmp }}/{{ inventory_hostname }}-generate.yaml"
  register: jahia2wp_generate_yaml_tmp

- name: jahia2wp.py generate
  when: wp_restore_from == 'generate' and not is_minishift_instance
  shell: "{{ jahia2wp_shell }} generate {{ wp_env }} {{ jahia2wp_url }} --extra-config={{ jahia2wp_generate_yaml_tmp.dest }}"
  environment: "{{ jahia2wp_env }}"

- include_tasks: generate-quick.yml
  when: wp_restore_from != 'generate' and not is_minishift_instance
