---


- name: DeploymentConfigs
  connection: local
  openshift:
    state: latest
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "{{name}}"
      name: "{{name}}"
      namespace: "myproject"
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            run: "{{name}}"
        spec:
          containers:
#            - env:
#              - name: WP_ENV
#                value: env
            - name: "{{name}}"
              env:
                - name: WORDPRESS_DB_NAME
                  value: "{{name}}"
                - name: WORDPRESS_DB_USER
                  value: root
                - name: WORDPRESS_DB_PASSWORD
                  value: "{{db_root_password | eyaml(eyaml_keys) }}"
                - name: WORDPRESS_DB_HOST
                  value: "{{db_ip}}"
              image: "wordpress:latest"
              ports:
                - containerPort: 80
                  protocol: TCP
              volumeMounts:
                - mountPath: /var/www/html
                  name: "nfsvol-{{name}}"
          volumes:
            - name: "nfsvol-{{name}}"
              persistentVolumeClaim:
                claimName: 'nfs-pvc-{{name}}'
      triggers:
        - type: ConfigChange

#        - type: ImageChange
#          imageChangeParams:
#            containerNames:
#            - "{{ name }}"
#            from:
#              kind: ImageStreamTag
#              name: "httpd:prod"
#              namespace: "myproject"
             
  tags: dc
