# Ansible playbook for the EPFL WordPress stack

- name: Initial checks
  hosts: all
  gather_facts: no    # Ansible facts are useless for this play
  tasks:
    - name: Check Ansible version
      run_once: true
      assert:
        that: "ansible_version.full is version_compare('2.6', '>=')"
        msg: |
          You must update Ansible to at least 2.6 to use this playbook.

- name: Minishift checks
  hosts: openshift-namespaces-blue
  gather_facts: no
  roles:
    - role : ../roles/minishift-checks


# Likewise, members of all-wordpress-instances are WordPress instances, not hosts. See the list in
# ../inventory/test/wordpress-instances (a plain file) and
# ../inventory/prod/wordpress-instances (an executable script, that lists
# them on standard output)
- name: WordPress instances
  hosts: all-wordpresses
  gather_facts: no   # But see ../roles/wordpress-instance/tasks/facts.yml
  roles:
    - role: ../roles/wordpress-instance

# In this play, "hosts" are not really hosts; rather, they are
# OpenShift namespaces. See the list in ../inventory/*/openshift-namespaces
- name: OpenShift namespaces
  hosts: all-openshift-namespaces
  gather_facts: no    # Ansible facts are useless for this play
  roles:
    - role: ../roles/wordpress-openshift-namespace


- name: Wordpress deployments
  hosts: all-wordpress-deployments
  gather_facts: no
  roles:
    - role : ../roles/wordpress-deployment


- name: Ansible Tower (AWX) configuration
  hosts: awx-poc-vpsi
  gather_facts: no    # Ansible facts are useless for this play
  roles:
    - role: ../roles/awx-poc-vpsi
