---



- name: "PersistentVolumeClaim"
  connection: local
  openshift:
    as_user: "system:admin"
    state: latest
    kind: PersistentVolumeClaim
    name: "nfs-pvc-{{name}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
      name: 'nfs-pvc-{{name}}'
    spec:
      accessModes:
      - ReadWriteMany
      resources:
         requests:
           storage: 1Gi
      selector:
          matchLabels:
              id: "{{name}}"
  tags: pvc