---
- name: "PersistentVolume"
  connection: local
  openshift:
    state: latest
    as_user: "system:admin"
    kind: PersistentVolume
    name: "nfs-pv-{{name}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
      name: 'nfs-pv-{{name}}'
      labels:
          id: "{{name}}"
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: '/wp/{{name}}'
        server: "{{nfs_ip}}"
        readOnly: false
  tags: pv
