---
# tasks for WordPress OpenShift namespaces


- name: "Disk usage report microservice"
  when: not is_minishift
  import_tasks: disk-usage-report.yml
  tags: diskusage


- name: "Image secret setup"
  when: is_minishift
  import_tasks: image-secret.yml
  


- name: "Images and builds"
  import_tasks: images.yml
  tags: images

- name: "DeploymentConfigs (previously known as pods)"
  when: not is_minishift
  include_tasks:
    file: deploymentconfig-httpd.yml
    # Because `include_tasks` is dynamic, tags don't auto-inherit.
    apply:
      tags: ["dc"]
  loop: "{{ DeploymentConfigs.httpd }}"
  loop_control:
    loop_var: dc
  tags: dc

- name: "Continuous integration"
  when: openshift_namespace == "wwp-test"
  include_tasks:
    file: continuous-integration.yml
    apply:
      tags:
        - ci
  # Multi-level tagging: `-t ci` will run all of continuous-integration.yml,
  # while `-t ci.jenkinsfile` will only load the BuildConfig with the
  # Jenkinsfile inside
  tags:
    - ci
    - ci.jenkinsfile

- name: "Management container (ssh server, PHP CLI)"
  when: not is_minishift
  import_tasks: mgmt.yml
  tags: mgmt

- name: blue-deployment
  when: is_minishift
  include_tasks:
    file: mnsft-mgmt-deployment.yml
