---
# Infrastructure deployment tasks
#
- name: Create wp directory
  connection: local
  shell: |
    set -e -x
    docker exec "{{nas_name}}" /bin/bash -c 'mkdir -p /"{{nfs_path}}"/wp ; chown -R "{{web_uid}}"."{{web_gid}}" /"{{nfs_path}}"/wp'

- name: pv
  import_tasks: "mnsft-mgmt-persistent-volume.yml"
  tags:
    - blue

- name: pvc
  import_tasks: "mnsft-mgmt-persistent-claim.yml"
  tags:
    - blue

- name: OpenProject deployment
  import_tasks: "mnsft-deploy-mgmt.yml"
  tags:
    - blue

- name: OpenProject service
  import_tasks: "mnsft-serve-mgmt.yml"
  tags:
    - blue
- name: OpenProject route
  import_tasks: "mnsft-route-mgmt.yml"
  tags:
    - blue

#