---



- name: "Service"
  openshift:
    state: latest
    kind: Service
    name: "{{dc.name}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
        name: "{{dc.name}}"
        labels:
          run: "{{dc.name}}"
        namespace: myproject
    spec:
        selector:
            run: "{{dc.name}}"
        ports:
        - port: 80
          protocol: TCP
          targetPort: 80
  tags: svc
