---


- name: "dc/{{ dc.name }}"
  openshift:
    state: latest
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "{{dc.name}}"
      name: "{{dc.name}}"
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
#      selector:
#        run: "{{dc.name}}"
      template:
        when: dc.db_ip is undefined
        metadata:
          labels:
            run: "{{dc.name}}"
        spec:
          containers:
            - env:
                - name: WORDPRESS_DB_NAME
                  value: "{{dc.db_name}}"
                - name: WORDPRESS_DB_USER
                  value: root
                - name: WORDPRESS_DB_PASSWORD
                  value: "{{dc.db_root_password | eyaml(eyaml_keys) }}"
                - name: WORDPRESS_DB_HOST
                  value: "{{dc.db_ip}}"
              image: 'wordpress:latest'
              name: "{{dc.name}}"
              volumeMounts:
                - mountPath: /var/www/html
                  name: "nfsvol-{{dc.name}}"
          volumes:
            - name: "nfsvol-{{dc.name}}"
              persistentVolumeClaim:
                claimName: 'nfs-pvc-{{dc.name}}'
      triggers:
        - type: ConfigChange
             
  tags: dc
