---



- name: "PersistentVolumeClaim"
  openshift:
    as_admin: true
    state: latest
    kind: PersistentVolumeClaim
    name: "nfs-pvc-{{dc.name}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
      name: 'nfs-pvc-{{dc.name}}'
    spec:
      accessModes:
      - ReadWriteMany
      resources:
         requests:
           storage: 1Gi
      selector:
          matchLabels:
              id: "{{dc.name}}"
  tags: pvc