---



- name: "PersistentVolume"
  openshift:
    as_user: "system:admin"
    state: latest
    kind: PersistentVolume
    name: "nfs-pv-{{dc.name}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
      name: 'nfs-pv-{{dc.name}}'
      labels:
          id: "{{dc.name}}"
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: '/wp/{{dc.name}}'
        server: "{{dc.nfs_ip}}"
        readOnly: false
  tags: pv
